# Copyright IBM Corp. 2014, 2025
# SPDX-License-Identifier: MPL-2.0

# Example configuration for IBM project
copyright:
  holder: "IBM Corp."
  start_year: 2014
  current_year: 2025
  format: "Copyright {{.Holder}} {{.StartYear}}, {{.CurrentYear}}"
  
license:
  enabled: true
  identifier: "MPL-2.0"
  format: "SPDX-License-Identifier: {{.Identifier}}"
files:
  # Only process files tracked by git (respects .gitignore)
  # Set to false to process all files in directory
  git_tracked: false
  
  # Path filtering (optional) - supports doublestar glob patterns
  # include_paths: ["internal/service/[a-g]*"]  # Only process paths matching these patterns
  # exclude_paths: [".github/**", "internal/service/s3*"]  # Skip paths matching these patterns
  # Patterns support: *, **, [a-z], {foo,bar}, etc.
  # Logic: no filters = all files, includes = only those, excludes = all except those, both = includes AND not excludes
  
  extensions:
    - ".go"
    - ".sh" 
    - ".py"
    - ".hcl"
    - ".tf"
    - ".yml"
    - ".yaml"
    - ".md"
    - ".html.markdown"

  # Smart extensions detect content type automatically
  # smart_extensions:
  #   - ".gtpl"    # Go templates - detects Go, Markdown, HCL, etc.
  #   - ".tmpl"    # Generic templates - detects actual content type
  
  # Smart extension indicators (scoring system for better detection)
  # smart_extension_indicators:
  #   - extension: ".md"
  #     patterns: ["## ", "### ", "```", "layout:", "subcategory:"]
  #     filenames: ["markdown", "md"]
  #   - extension: ".tf"  
  #     patterns: ["resource \"", "variable \"", "output \"", "provider \""]
  #     filenames: [".tf.", "terraform"]
  #   - extension: ".go"
  #     patterns: ["package ", "func ", "import ("]
  #     filenames: []
  
  comment_styles:
    go: "//"
    sh: "#"
    py: "#" 
    hcl: "#"
    tf: "#"
    yml: "#"
    yaml: "#"
    md: "<!--"
    html_markdown: "<!--"
  
  below_frontmatter:
    - ".md"
    - ".html.markdown"

detection:
  skip_generated: true
  generated_patterns:
    - "Code generated"
    - "DO NOT EDIT"
  
  replace_patterns:
    - "Copyright.*HashiCorp.*"
  
  # Limit how many lines to scan for existing copyright (0 = scan entire file)
  # Prevents finding copyrights deep in files (e.g., test cases)
  max_scan_lines: 20
  
  # Require copyright to be at the very top (after shebang/frontmatter)
  # If false, copyright can be anywhere within max_scan_lines
  require_at_top: true
third_party:
  action: "above"
  patterns:
    - "Copyright.*[a-zA-Z0-9].*"
